server:
  port: 8081

spring:
  application:
    name: menu-service
  config:
    import: "consul:"
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: menuservice_db
#      username: devuser
#      password: devpassword
#      authentication-database: admin
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        format: yaml
        prefix: config
        default-context: menu-service
        profile-separator: '-'
        data-key: application.yml
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s

management:
  endpoints:
    web:
      exposure:
        include: health, env, configprops

#debug: true
#logging:
#    level:
#        org.springframework.cloud.consul: DEBUG
#        org.springframework.cloud.consul.discovery: DEBUG
#        org.springframework.cloud.consul.config: DEBUG
#        org.springframework.cloud.consul.endpoint: DEBUG
#        org.springframework.cloud.consul.serviceregistry: DEBUG
#        org.springframework.cloud.consul.config.ConsulPropertySourceLocator: DEBUG